ALTER TABLE DISGROUP DROP FOREIGN KEY FK_DISGROUP_CREATED
ALTER TABLE MEMBER DROP FOREIGN KEY FK_MEMBER_ID
ALTER TABLE USER2MOVIE DROP FOREIGN KEY FK_USER2MOVIE_USER
ALTER TABLE COMMENT2USER DROP FOREIGN KEY FK_COMMENT2USER_CID
ALTER TABLE COMMENT2PEOPLE DROP FOREIGN KEY FK_COMMENT2PEOPLE_CID
ALTER TABLE GROUP2MEMBER DROP FOREIGN KEY FK_GROUP2MEMBER_USER_ID
ALTER TABLE GROUP2MEMBER DROP FOREIGN KEY FK_GROUP2MEMBER_GROUP_ID
DROP TABLE DISGROUP
DROP TABLE POPULARMOVIE
DROP TABLE USER
DROP TABLE MEMBER
DROP TABLE USER2MOVIE
DROP TABLE COMMENT
DROP TABLE COMMENT2USER
DROP TABLE COMMENT2PEOPLE
DROP TABLE GROUP2MEMBER
